### ISSUE TITLE
Shell Jobs randomly getting 'stuck'

### ISSUE THREAD

**Issue by giggsey** [distribworks/dkron#1483]
## Describe the bug

Some shell jobs are randomly getting stuck in the 'busy' state, and don't clear until we restart the dkron agent.

The job processes launched by dkron agent are finishing as expected and exiting cleanly. Dkron doesn't notice, so the job stays in the 'busy' status, and further executions don't happen (we prevent concurrency).

We recently upgraded from 3.2.0 to 3.2.7, and this problem is now happening randomly with some of our jobs.

## Job Description

```json
{

    "id": "cloud_sync_user-data_private_app-server",
    "name": "cloud_sync_user-data_private_app-server",
    "displayname": "",
    "timezone": "",
    "schedule": "@every 5m",
    "owner": "cloud_sync",
    "owner_email": "",
    "success_count": 134712,
    "error_count": 506,
    "last_success": "2024-02-22T09:50:48.739347143Z",
    "last_error": "2024-02-22T09:40:03.273059208Z",
    "disabled": false,
    "tags": {
        "my_tag": "private_app-server:1"
    }

    ,
    "metadata": null,
    "retries": 0,
    "dependent_jobs": null,
    "parent_job": "",
    "processors": {}

    ,
    "concurrency": "forbid",
    "executor": "shell",
    "executor_config": {
        "command": "/usr/local/bin/dkron_run 0002 \"my-daemons\" \"/var/log/dkron-jobs/cloud_sync_user-data_private_app-server.log\" \"PATH=/sbin:/bin:/usr/sbin:/usr/bin /path/cloud_sync/bin/sync user-data -vvv\""
    }

    ,
    "status": "success",
    "next": "2024-02-22T09:58:52Z",
    "ephemeral": false,
    "expires_at": null
}

```

## Logs

The job took around ~15 seconds to execute (I can see from the logs that my dkron_run script generates).

```
2024-02-22T01:48:52.020093+00:00 HR-P-APP-2 dkron[1119]: time="2024-02-22T01:48:52Z" level=info msg="grpc_agent: Starting job" job=cloud_sync_user-data_private_app-server node=HR-P-APP-2.production.my.network
2024-02-22T01:48:52.020272+00:00 HR-P-APP-2 dkron[1119]: time="2024-02-22T01:48:52Z" level=debug msg="grpc_agent: calling executor plugin" node=HR-P-APP-2.production.my.network plugin=shell
2024-02-22T01:48:52.020993+00:00 HR-P-APP-2 dkron[1119]: time="2024-02-22T01:48:52Z" level=debug msg="2024/02/22 01:48:52 shell: going to run /usr/local/bin/dkron_run 0002 \"my-daemons\" \"/var/log/dkron-jobs/cloud_sync_user-data_private_app-server.log\" \"PATH=/sbin:/bin:/usr/sbin:/usr/bin /path/cloud_sync/bin/sync user-data -vvv\"" node=HR-P-APP-2.production.my.network subsystem_name=plugins.dkron-executor-shell

2024-02-22T01:49:07.300497+00:00 HR-P-APP-2 dkron[1119]: time="2024-02-22T01:49:07Z" level=debug msg="2024/02/22 01:49:07 NewProcess err: process does not exist" node=HR-P-APP-2.production.my.network subsystem_name=plugins.dkron-executor-shell
2024-02-22T01:49:07.300664+00:00 HR-P-APP-2 dkron[1119]: time="2024-02-22T01:49:07Z" level=debug msg="2024/02/22 01:49:07 Error getting pid statistics: process does not exist" node=HR-P-APP-2.production.my.network subsystem_name=plugins.dkron-executor-shell
```

Logs for a good job that ran at around the same time. This other job took less than a second to execute.

```
2024-02-22T01:48:53.019439+00:00 HR-P-APP-2 dkron[1119]: time="2024-02-22T01:48:53Z" level=info msg="grpc_agent: Starting job" job=cloud_sync-alert-data_private_app-server node=HR-P-APP-2.production.my.network
2024-02-22T01:48:53.020427+00:00 HR-P-APP-2 dkron[1119]: time="2024-02-22T01:48:53Z" level=debug msg="grpc_agent: calling executor plugin" node=HR-P-APP-2.production.my.network plugin=shell
2024-02-22T01:48:53.021941+00:00 HR-P-APP-2 dkron[1119]: time="2024-02-22T01:48:53Z" level=debug msg="2024/02/22 01:48:53 shell: going to run /usr/local/bin/dkron_run 0002 \"my-daemons\" \"/var/log/dkron-jobs/cloud_sync-alert-data_private_app-server.log\" \"PATH=/sbin:/bin:/usr/sbin:/usr/bin /path/cloud_sync/bin/sync alert-data -vvv\"" node=HR-P-APP-2.production.my.network subsystem_name=plugins.dkron-executor-shell
2024-02-22T01:48:56.043127+00:00 HR-P-APP-2 dkron[1119]: time="2024-02-22T01:48:56Z" level=debug msg="2024/02/22 01:48:56 NewProcess err: process does not exist" node=HR-P-APP-2.production.my.network subsystem_name=plugins.dkron-executor-shell
2024-02-22T01:48:56.043387+00:00 HR-P-APP-2 dkron[1119]: time="2024-02-22T01:48:56Z" level=debug msg="2024/02/22 01:48:56 Error getting pid statistics: process does not exist" node=HR-P-APP-2.production.my.network subsystem_name=plugins.dkron-executor-shell
2024-02-22T01:48:56.043548+00:00 HR-P-APP-2 dkron[1119]: time="2024-02-22T01:48:56Z" level=debug msg="2024/02/22 01:48:56 shell: Command output " node=HR-P-APP-2.production.my.network subsystem_name=plugins.dkron-executor-shell
2024-02-22T01:48:57.591651+00:00 HR-P-APP-2 dkron[1119]: time="2024-02-22T01:48:57Z" level=info msg="2024/02/22 01:48:57 [DEBUG] memberlist: Initiating push/pull sync with: HR-P-SQL-3.production.my.network 192.168.181.23:8946"

```

## Specifications

 - OS: AlmaLinux 9.3
 - Version: 3.2.7

**Comment by morgan-atproperties** [comment]
We are seeing the same thing.  We were running 3.2.6 previously, and we're going to roll back to that version.

**Comment by mladoi** [comment]
Having the same issue with 3.2.7. 
Job is merely calling a `redis-cli publish check 1` every 5 minutes. 
Approx. 1 in 1000 job executions get stuck in busy state forever.
Even setting `timeout` in `executor_config` doesn't change the busy state.

**Comment by morgan-atproperties** [comment]
Rolling back to 3.2.6 fixed it for us.

**Comment by morgan-atproperties** [comment]
I tried out the latest DKRON version (4.0.2), hoping that it fixes the issue.  It doesn't.  The bug fills up our busy tab, so we're stuck on the old version.

I just put together a docker compose stack to demonstrate the bug, based on the redis command provided by @mladoi.  Here is a repository with the demonstration: [dkron-busy-bug](https://github.com/morgan-atproperties/dkron-busy-bug)  I think it's clear that this bug was introduced in 3.2.7.

**Comment by vcastellm** [comment]
Thanks @morgan-atproperties for reporting this and preparing the demo repo, we're on it

**Comment by mrhackcz** [comment]
I think, the problem persists:| @vcastellm t

Tested in morgan's demo repo, and confirmed on our stage environment (single node). So again downgraded back to working 3.2.6

![Image](https://github.com/user-attachments/assets/1e268a47-dce4-42c9-937d-bb79d9ebe689)

**Comment by vcastellm** [comment]
I doublechecked it again and yes, it's failing, reopening the issue.

**Comment by vcastellm** [comment]
The issue is fixed in https://github.com/distribworks/dkron/pull/1675, this one was tricky to find.

**Comment by mrhackcz** [comment]
Hello @vcastellm ,

We are still encountering this issue, though at a reduced frequency compared to before. However, jobs continue to get stuck intermittently.

I’ve collected debug logs, but they don’t reveal anything noteworthy. Environment details:

Staging server
Ubuntu 22.04.5 LTS
Deb package v4.0.4
Single-node setup

All jobs have concurrency disabled and use the shell executor (launching PHP programs). Total jobs: 520 (only 200 enabled).

I attempted to replicate the issue in Morgan’s test repository without success. Our production environment uses an identical setup with one exception: 3 nodes instead of 1. On version 3.2.6, the system functions almost flawlessly (0.01% of executions fail with `rpc error: code = Unknown desc = timeout waiting for connection info`).

```
user@server:/etc/dkron$ cat debug.log | grep 1743153120082316246
Mar 28 10:12:00 server.com dkron[2886695]: time="2025-03-28T10:12:00+01:00" level=debug msg="grpc: received execution stream" key=1743153120082316246-server.com node=server.com
Mar 28 10:12:00 server.com dkron[2886695]: time="2025-03-28T10:12:00+01:00" level=debug msg="grpc: Received SetExecution" execution=1743153120082316246-server.com node=server.com
Mar 28 10:12:00 server.com dkron[2886695]: time="2025-03-28T10:12:00+01:00" level=debug msg="store: Setting key" execution="executions:console-cron-8:1743153120082316246-server.com" finished="0001-01-01 00:00:00 +0000 UTC" job=console-cron-8 node=server.com
Mar 28 10:12:01 server.com dkron[2886695]: time="2025-03-28T10:12:01+01:00" level=debug msg="grpc: received execution stream" key=1743153120082316246-server.com node=server.com
Mar 28 10:12:01 server.com dkron[2886695]: time="2025-03-28T10:12:01+01:00" level=debug msg="grpc: received execution stream" key=1743153120082316246-server.com node=server.com
Mar 28 10:12:01 server.com dkron[2886695]: time="2025-03-28T10:12:01+01:00" level=debug msg="grpc: received execution stream" key=1743153120082316246-server.com node=server.com
Mar 28 10:12:01 server.com dkron[2886695]: time="2025-03-28T10:12:01+01:00" level=debug msg="grpc: received execution stream" key=1743153120082316246-server.com node=server.com

user@server:/etc/dkron$ cat debug.log | grep 1743153300061924610
Mar 28 10:15:00 server.com dkron[2886695]: time="2025-03-28T10:15:00+01:00" level=debug msg="grpc: received execution stream" key=1743153300061924610-server.com node=server.com
Mar 28 10:15:00 server.com dkron[2886695]: time="2025-03-28T10:15:00+01:00" level=debug msg="grpc: Received SetExecution" execution=1743153300061924610-server.com node=server.com
Mar 28 10:15:01 server.com dkron[2886695]: time="2025-03-28T10:15:01+01:00" level=debug msg="store: Setting key" execution="executions:console-cron-10:1743153300061924610-server.com" finished="0001-01-01 00:00:00 +0000 UTC" job=console-cron-10 node=server.com

user@server:/etc/dkron$ cat debug.log | grep 1743153360073706021
Mar 28 10:16:00 server.com dkron[2886695]: time="2025-03-28T10:16:00+01:00" level=debug msg="grpc: received execution stream" key=1743153360073706021-server.com node=server.com
Mar 28 10:16:00 server.com dkron[2886695]: time="2025-03-28T10:16:00+01:00" level=debug msg="grpc: Received SetExecution" execution=1743153360073706021-server.com node=server.com
Mar 28 10:16:00 server.com dkron[2886695]: time="2025-03-28T10:16:00+01:00" level=debug msg="store: Setting key" execution="executions:console-cron-127:1743153360073706021-server.com" finished="0001-01-01 00:00:00 +0000 UTC" job=console-cron-127 node=server.com
```

![Image](https://github.com/user-attachments/assets/f770bc8d-7f46-45b1-8f5b-581eefe61089)
![Image](https://github.com/user-attachments/assets/b679e84e-e246-45e9-a769-6ea3c812ae4c)
![Image](https://github.com/user-attachments/assets/ae75fade-276a-49e3-b9bf-49a32edd3e71)

**Comment by mrhackcz** [comment]
Any acknowledgment @vcastellm ? Do you think I can somehow help with debugging?

**Comment by vcastellm** [comment]
So with version 4.0.4 how much jobs gets stuck in busy?

**Comment by mrhackcz** [comment]
> So with version 4.0.4 how much jobs gets stuck in busy?

After 24 hours of upgrading to version 4.0.4, there are 41 stuck jobs. The total number of jobs is 531, and 201 of them are enabled.

It's a single node, Ubuntu 22.04, kernel 6.1.86, dkron 4.0.4 as a package from the repository. None of the "busy" jobs are actually running on the server, so I can't kill them. The only "solution" is to restart the dkron service.

**Comment by EmilioMoreno** [comment]
Happens here too, quite easily, i usually have to restart some of the nodes 2 or 3 times per week. If you need some help for testing let me know

**Comment by mrhackcz** [comment]
Update:

We are running ~300 active jobs on our staging server. Initially, all jobs were configured with `shell: true`. Each job executed a small wrapper script `console.sh`. Half of them were for [PHP Phalcon](https://phalcon.io/en-us)  and other half for Symfony console:

```
#!/bin/sh
php bootstraps/cli.php "$@"
```
As a result, the process tree looked like this:
`dkron-shell > sh > console.sh > sh > php ...`

I changed all jobs to use `shell: false` and updated the cmd to run directly, e.g., instead of `console.sh CMD` I now use:
`php bootstraps/cli.php CMD`.

We also upgraded to Dkron 4.0.5 (note: this version is still not available in the Debian repository @vcastellm ) and configured `~` in the seconds field of the schedule expression. With this change, job execution times became much more distributed. Previously, we had situations where ~100 jobs could start exactly at 08:00:00.

At first, this looked very promising, but after five days, the stuck jobs issue reappeared, although it now affects only a very small number of jobs.

Additional info:

- Dkron is not running as the root user on this server, but as a dedicated unprivileged user.
- The debug log shows nothing related when this happens.
- The stuck jobs remain listed under the “Busy” tab in the web UI with `Empty output`

**Comment by EmilioMoreno** [comment]
@mrhackcz do you know if the improvement can be related to upgrade to 4.0.5 or do you think this is shell:false which provides more reliability? i am restarting every agent on a daily basis as this prevents the jobs to be stuck and unblocks the stuck ones.

**Comment by mrhackcz** [comment]
> [@mrhackcz](https://github.com/mrhackcz) do you know if the improvement can be related to upgrade to 4.0.5 or do you think this is shell:false which provides more reliability? i am restarting every agent on a daily basis as this prevents the jobs to be stuck and unblocks the stuck ones.

It's definitely not related to 4.0.5. I tried this version before, and the problem still occurs in that version. I can recommend downgrading to 3.2.6, which is far more reliable - we use it on production nodes. I'm thinking about trying another software, probably cronicle.

**Comment by vcastellm** [comment]
> this version is still not available in the Debian repository

thx, just pushed the packages

**Comment by vcastellm** [comment]
Tnx for reporting @mrhackcz and not happy to read the situation, trying to spot the issue in the following days.

**Comment by EmilioMoreno** [comment]
@

> It's definitely not related to 4.0.5. I tried this version before, and the problem still occurs in that version. I can recommend downgrading to 3.2.6, which is far more reliable - we use it on production nodes. I'm thinking about trying another software, probably cronicle.

Thanks. I am afraid i can not downgrade to 3.2.6, it has other bugs  which forced us to upgrade, so we are somehow stuck untill this bug is totally fixed

**Comment by vcastellm** [comment]
At this moment we've been unable to reproduce the issue, while we continue trying it we've decided to release https://github.com/distribworks/dkron/releases/tag/v4.0.6 removing Prometheus metrics from the shell executor, please, @EmilioMoreno and @morgan-atproperties @giggsey @mrhackcz and others, test with this version and check if it manages to fix the issue so we know a bit more where exactly the bug is.

**Comment by morgan-atproperties** [comment]
> At this moment we've been unable to reproduce the issue, while we continue trying it we've decided to release https://github.com/distribworks/dkron/releases/tag/v4.0.6 removing Prometheus metrics from the shell executor, please, [@EmilioMoreno](https://github.com/EmilioMoreno) and [@morgan-atproperties](https://github.com/morgan-atproperties) [@giggsey](https://github.com/giggsey) [@mrhackcz](https://github.com/mrhackcz) and others, test with this version and check if it manages to fix the issue so we know a bit more where exactly the bug is.

@vcastellm I'll try to get us upgraded soon!  We're currently still on 3.2.6.

**Comment by mrhackcz** [comment]
@vcastellm I’d say, version 4.0.6 should be removed quickly 😅 . Now all the jobs that start get stuck and none of them finish. Or rather, they do run, but they remain busy.

```
vader@deathstar:~/work$ curl -s https://dkron.xx.yy/v1/busy | jq .[].id | wc -l
200
```

**Comment by vcastellm** [comment]
Yeah @mrhackcz sorry my mistake 💩 , going to create a new release, fixed in https://github.com/distribworks/dkron/pull/1813

**Comment by mrhackcz** [comment]
@vcastellm [4.0.7] Now there is another problem with all jobs. Every job ends as a Zombie:
https://pastebin.vshosting.cz/?13e89f979e5933d6#5EqjtbT3xBLYoovgvmD8zmgH5KqazFkaavEdjRsFZ83W

**Comment by vcastellm** [comment]
Thanks @mrhackcz you're right, this code has some tricky parts not easy to test, fixed now in #1816 , hotfix release incoming.

**Comment by vcastellm** [comment]
Released the hotfix https://github.com/distribworks/dkron/releases/tag/v4.0.8 and added extensive testing

**Comment by EmilioMoreno** [comment]
i will update my test version to this one;  @mrhackcz do you have any feedback in terms of the bug on this one?

**Comment by mrhackcz** [comment]
Still testing on staging environment and partially on production. It looks good so far on 4.0.8 🔥 I will post update next week.

**Comment by mrhackcz** [comment]
I'd say the issue no longer appears. Occasionally, a job still fails with the following error message:

```
grpc: Error on execution streaming, agent connection was abruptly terminated: rpc error: code = Internal desc = grpc: error while marshaling: marshaling types.AgentRunStream: size mismatch (see https://github.com/golang/protobuf/issues/1609): calculated=215, measured=549
```

However, this was already happening in version 3.2.6, just with less verbose logging.

IMHO, this issue can be closed as resolved. Thank you @vcastellm !

**Comment by EmilioMoreno** [comment]
@mrhackcz thanks!

**Comment by vcastellm** [comment]
Closing because it's fixed for now
