### ISSUE TITLE
Skipped Jobs

### ISSUE THREAD

**Issue by agarwal-nitesh** [distribworks/dkron#633]
1. A job is not picked for the next run and so miss all subsequent runs. 
2. Also when a job is run manually using the play button on the dkron dashboard the next run time it picks is the current time (I have been using @every construct of the cronspec).
3. On using the API doc to create new jobs, the first run is executed successfully but next run time is not updated to so all subsequent runs fail.

1. Create a new job using @every construct of the cronspec, second and the following runs fail.
2. Use the play button on the dashboard. Next run time will be picked as the current time.

 - OS: centos
 - Version 2 rc9
<img width="1034" alt="Screenshot 2019-11-18 at 9 56 40 AM" src="https://user-images.githubusercontent.com/37532307/69024938-fe336600-09ea-11ea-91bd-5d8f7cbec673.png">

**Comment by victorcoder** [comment]
@agarwal-nitesh according to the screenshot, next execution times are shown correctly. I don't understand what's the issue. Could you elaborate?

**Comment by agarwal-nitesh** [comment]
The job was not picked for execution at the next run time. The screenshot I have taken is way past the next execution time.

**Comment by geoffjukes** [comment]
@victorcoder I just upgraded from 1.2.5 to 2.0.0-rc9 and I am having the same issue:

![image](https://user-images.githubusercontent.com/1959570/69166217-bde5ed80-0aa7-11ea-9976-8eab911c09dd.png)

The first run executed automatically, but none sine (the running job in the screenshot was manually triggered by me)

**Comment by geoffjukes** [comment]
@victorcoder I've set the log level to debug and restarted Dkron.

At least one job has run once since the restart. I am waiting to see if it stops after the first scheduled run.

**Comment by geoffjukes** [comment]
It looks like the events will run once, according to schedule, after a restart. Then nothing.

**Comment by victorcoder** [comment]
Could you navigate to `/debug/vars` in the leader node and check for the `scheduler_started` var? what it reports?

**Comment by geoffjukes** [comment]
@victorcoder `scheduler_started` on the leader shows a value of `1`

**Comment by victorcoder** [comment]
I'm not able to reproduce it, could you try to reproduce it in this test instance? http://test.dkron.io:8080

**Comment by geoffjukes** [comment]
@victorcoder I target my jobs using tags, and forbid concurrency - could that be a contributing factor?

Here is the Job spec for one of the jobs:

```
{
  "name": "rpc-process-book-autocut",
  "executor": "shell",
  "executor_config": {
    "command": "(cd /opt/rpc/schedule; .env/bin/python rpc/autocut.py)",
    "run_as_user": "runner",
    "shell": "true"
  },
  "schedule": "0 */15 6-18 * * MON-FRI",
  "concurrency": "forbid",
  "owner" : "Geoff Jukes",
  "disabled": false,
  "tags": {
      "runner": "manager:1"
  }
}
```

and the server config:

```
encrypt: DELETEDFORSAFETY==
server: True
datacenter: ash
region: west
data-dir: dkron.data
log-level: error
bootstrap-expect: 4
retry-join:
  - 172.16.1.71
  - 172.16.1.72
  - 172.16.1.73
  - 172.16.1.74
tags:
  runner: manager
```

**Comment by geoffjukes** [comment]
@victorcoder Modified version of the above seemed to work just fine on your system (I experimented with different schedules too). Job name `test-geoffjukes`

**Comment by geoffjukes** [comment]
@victorcoder I shut down my instances, deleted `/dkron.data` and restarted the servers.

1. Noticed that no leader was elected (I use Salt so I issued the `start` at the same time on all hosts).
2. Restarted the nodes one at a time, and a leader was elected.
3. Imported a test jon that executes every minute, no concurrency, targetted to 1 server (per above)
4. Job ran at first schedule *twice* on the same node in rapid succession.
5. Has not run since.

![image](https://user-images.githubusercontent.com/1959570/69199432-c7457900-0aec-11ea-9c6a-0785a4a10f60.png)

Please let me know if there is anything I can do to assist testing this. I inadvertantly upgraded from 1.2.5 to 2.0, and I can roll back if I need to.

**Comment by agarwal-nitesh** [comment]
Also, I changed the concurrency from `forbid` to `allow` for the jobs which say otherwise in the logs.

```Nov 20 11:40:49 ip-10-0-5-99.ap-southeast-1.compute.internal dkron[2143]: time="2019-11-20T11:40:49+05:30" level=info msg="job: Skipping concurrent execution" concurrency=forbid job=alerts job_status=running node=ip-10-0-5-99.ap-southeast-1.compute.internal
Nov 20 11:40:50 ip-10-0-5-99.ap-southeast-1.compute.internal dkron[2143]: time="2019-11-20T11:40:50+05:30" level=info msg="job: Skipping concurrent execution" concurrency=forbid job=driver-els job_status=running node=ip-10-0-5-99.ap-southeast-1.compute.internal
Nov 20 11:40:51 ip-10-0-5-99.ap-southeast-1.compute.internal dkron[2143]: time="2019-11-20T11:40:51+05:30" level=info msg="job: Skipping concurrent execution" concurrency=forbid job=employee-els job_status=running node=ip-10-0-5-99.ap-southeast-1.compute.internal
Nov 20 11:40:53 ip-10-0-5-99.ap-southeast-1.compute.internal dkron[2143]: time="2019-11-20T11:40:53+05:30" level=info msg="job: Skipping concurrent execution" concurrency=forbid job=location-els job_status=running node=ip-10-0-5-99.ap-southeast-1.compute.internal
Nov 20 11:40:56 ip-10-0-5-99.ap-southeast-1.compute.internal dkron[2143]: time="2019-11-20T11:40:56+05:30" level=info msg="job: Skipping concurrent execution" concurrency=forbid job=vehicle-els job_status=running node=ip-10-0-5-99.ap-southeast-1.compute.internal
Nov 20 11:41:15 ip-10-0-5-99.ap-southeast-1.compute.internal dkron[2143]: time="2019-11-20T11:41:15+05:30" level=info msg="2019/11/20 11:41:15 [WARN] serf: Query queue depth: 884"```

**Comment by victorcoder** [comment]
@agarwal-nitesh yes this is due to a bug fixed in https://github.com/distribworks/dkron/pull/639

**Comment by agarwal-nitesh** [comment]
> @victorcoder `scheduler_started` on the leader shows a value of `1`.
> 
> I run a 4-node cluster, and the other 3 show a value of `0`. (added for completeness)

I am using single node setup and `scheduler_started` is `1` and still having the issue.

**Comment by agarwal-nitesh** [comment]
I can share with you the dashboard endpoint over email if it helps to debug the issue.

**Comment by victorcoder** [comment]
No worries @agarwal-nitesh, thanks.

@agarwal-nitesh @geoffjukes I detected the bug, it's a regression introduced in https://github.com/distribworks/dkron/pull/630

Fix incoming, expect a new release in the following hours

**Comment by geoffjukes** [comment]
rc10 works perfectly. Thanks @victorcoder
